"""Migration file classification."""

from __future__ import annotations

import re
from pathlib import Path

MIGRATION_PEEK_BYTES = 65536


def read_migration_file_peek(path: Path) -> str:
    try:
        with path.open("rb") as handle:
            data = handle.read(MIGRATION_PEEK_BYTES)
    except OSError:
        return ""
    if b"\x00" in data:
        return ""
    return data.decode("utf-8", errors="ignore")


def classify_migration_file(path: Path, source_root: Path) -> list[str]:
    rel = path.relative_to(source_root)
    parts = [part.lower() for part in rel.parts]
    name = path.name.lower()
    suffix = path.suffix.lower()
    tags: set[str] = set()

    if any(part in {".git", "node_modules", "__pycache__", ".venv", "venv", ".idea", ".vscode"} for part in parts):
        tags.add("machine-local-risk")
    if name in {".ds_store", "thumbs.db"}:
        tags.add("machine-local-risk")
    if re.search(r"(secret|credential|password|passwd|token|apikey|api-key|private-key)", "/".join(parts)):
        tags.add("credential-or-private-risk")
    if name.startswith(".env") or suffix in {".pem", ".key", ".p12", ".pfx"}:
        tags.add("credential-or-private-risk")

    provider_parts = {".claude", ".codex", ".agents"}
    if any(part in provider_parts for part in parts) or name in {"agents.md", "claude.md"}:
        tags.add("provider-surface")
    if any(part in provider_parts for part in parts) and name in {"settings.json", "config.json", "config.toml", "settings.toml"}:
        tags.add("provider-settings")
    if any(part in {"commands", "slash-commands", "hooks"} for part in parts):
        tags.add("provider-command")

    if ".hydra-framework" in parts:
        tags.add("hydra-project")
    if ".hydra-framework.local" in parts:
        tags.add("private-hydra-risk")

    if suffix in {".md", ".markdown", ".txt", ".rst", ".adoc"}:
        text = read_migration_file_peek(path)
        lowered = text.lower()
        joined = "/".join(parts)
        if "hydra_id:" in text or "hydra://" in text:
            tags.add("hydra-object")
        if re.search(r"(prompt|instruction|agent|claude|codex|ai[-_ ]?rules|system[-_ ]?prompt)", joined):
            tags.add("ai-prompt-or-rules")
        if re.search(r"(task|todo|board|session|handoff|checkpoint|memory)", joined):
            tags.add("task-or-session-state")
        if re.search(r"(docs?|wiki|knowledge|decision|architecture|adr)", joined):
            tags.add("docs-or-wiki")
        if "generated by" in lowered or "do not edit" in lowered:
            tags.add("generated-surface")
    else:
        text = read_migration_file_peek(path)
        if "hydra_id:" in text or "hydra://" in text:
            tags.add("hydra-object")

    if suffix in {".pdf", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".doc", ".docx", ".ppt", ".pptx", ".xls", ".xlsx"}:
        tags.add("raw-source-material")
    if not tags:
        tags.add("source-material")
    return sorted(tags)
